site_author: B. van Wetten
copyright: Copyright &copy; 2024 besqua.red<br/>
edit_uri: https://github.com/tainrs/site/edit/main/docs/
repo_name: tainrs
repo_url: https://github.com/tainrs/site

site_description: Documentation for all Docker images maintained by tainrs.
site_name: tainrs.dev
site_url: https://tainrs.dev

extra:
  social:
  - icon: fontawesome/solid/heart
    link: 'https://tainrs.dev/donate'
    name: Donate
  - icon: fontawesome/brands/docker
    link: 'https://tainrs.dev/dockerhub'
    name: Docker
  - icon: fontawesome/brands/github
    link: 'https://tainrs.dev/github'
    name: GitHub

plugins:
  - redirects:
      redirect_maps:
        dockerhub.md: 'https://hub.docker.com/u/tainrs'
        github.md: 'https://github.com/tainrs'
        donate.md: 'https://tainrs.dev/#donations'

theme:
    name: material
    logo: img/tainrs-logo.png
    features:
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    - content.action.edit
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.code.select
    - content.code.annotate

    palette:

      # Palette toggle for light mode
      - scheme: default
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode

      # Palette toggle for dark mode
      - scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to light mode

nav:
- Home: index.md
- Containers:
  - Base Images:
    - tainrs/base: tainrs/base.md
  - Apps:
    - tainrs/lidarr: tainrs/lidarr.md
    - tainrs/plex: tainrs/plex.md
    - tainrs/prowlarr: tainrs/prowlarr.md
    - tainrs/radarr: tainrs/radarr.md
    - tainrs/readarr: tainrs/readarr.md
    - tainrs/sonarr: tainrs/sonarr.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js
  - javascripts/loadJSON.js

extra_css:
  - stylesheets/extra.css
